core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz.urls')),
    path('', include('quiz_session.urls')),
]

quiz/urls.py
from . import views
from django.urls import path


app_name = 'quiz'
urlpatterns = [
    path('', views.QuizListView.as_view(),name='quiz-list'),
    path('<uuid:pk>', views.QuizDetailView.as_view(),name='quiz-detail'),
    
    path('create', views.QuizCreateView.as_view(),name='quiz-create'),
    path('<uuid:pk>/delete', views.QuizDeleteView.as_view(),name='quiz-delete'),
    path('<uuid:pk>/edit', views.QuizUpdateView.as_view(),name='quiz-update'),
    
    path('<uuid:quiz_pk>/question/<str:model_name>/create', views.QuestionCreateUpdateView.as_view(),name='question-create'),
    path('<uuid:quiz_pk>/question/<str:model_name>/<int:pk>', views.QuestionCreateUpdateView.as_view(),name='question-update'),
    path('question/<int:pk>/delete', views.QuestionDeleteView.as_view(),name='question-delete'),
    
    path('<int:question_id>/answer/create', views.AnswerCreateView.as_view(),name='answer-create'),
    
]

quiz_session/urls.py
from . import views
from django.urls import path


app_name = 'quiz_session'


urlpatterns = [
    path('<uuid:quiz_pk>/create_session', views.CreateQuizSessionView.as_view(),name='create-session'),
    path('host_live/<uuid:session_pk>', views.AdminSessionView.as_view(),name='admin-view-session'),
    path('join', views.JoinSessionView.as_view(),name='join-session'),
    path('complete', views.ClientSessionView.as_view(),name='client-view-session'),
]

quiz/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth import get_user_model
from django.urls import reverse

import uuid

# Create your models here.






class Quiz(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    title = models.CharField(max_length=255)
    creator = models.ForeignKey(get_user_model(),on_delete=models.CASCADE,related_name='quizzes')
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']
    
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse(
        'quiz:quiz-detail',
        args=[self.id]
        )
    



class Question(models.Model):
    quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE,related_name='questions')
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
        limit_choices_to={
            'model__in': ('textquestion', 'optionquestion','booleanquestion' )
        },
    )
    object_id = models.PositiveIntegerField()
    item = GenericForeignKey('content_type', 'object_id')
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['created']
        

class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE,related_name='answers')
    title = models.CharField(max_length=255) 
    
    def __str__(self):
        return self.title
    class Meta:
        unique_together = ('question','title')
    
class QuestionBase(models.Model):
    image = models.ImageField(upload_to='images',null=True,blank=True)
    time_limit = models.IntegerField(default=30)
    title = models.CharField(max_length=255) 
    
    def __str__(self):
        return self.title    
     
    class Meta:
        abstract = True
       
    
    
class TextQuestion(QuestionBase):
    pass
    
    
class BooleanQuestion(QuestionBase):
    pass


class OptionQuestion(QuestionBase):
    pass
    


class Option(models.Model):
    question = models.ForeignKey(OptionQuestion,on_delete=models.CASCADE,related_name='options')
    title = models.CharField(max_length=255) 
    
    
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['question']
    

 

quiz/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from . import models

OptionFormSet = inlineformset_factory(
    models.OptionQuestion,
    models.Option,
    fields=['title', ],
    extra=2,
    can_delete=True,
    
)

quiz/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import ListView,DetailView,CreateView,View,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.views.generic.base import TemplateResponseMixin
from django.forms.models import modelform_factory
from django.apps import apps
from django.http import Http404,HttpResponseRedirect,HttpResponse
from django import forms
from django.forms import formsets
from django.urls import reverse_lazy,reverse
from django.db.utils import IntegrityError
from django.contrib import messages
from django.db.utils import IntegrityError

import random

from .forms import OptionFormSet
from . import models

# Create your views here.

class QuizListView(ListView):
    model = models.Quiz
    context_object_name = 'quizzes'
    template_name ='quiz/quiz_list.html'
    
class QuizDetailView(DetailView):
    model = models.Quiz
    context_object_name = 'quiz'
    
class QuizUpdateView(LoginRequiredMixin,UpdateView):
    model = models.Quiz
    fields = ['title']
    template_name = 'quiz/quiz_form.html'
    
class QuizCreateView(LoginRequiredMixin,CreateView):
    model = models.Quiz
    fields = ['title']
    template_name = 'quiz/quiz_form.html'
    
    def form_valid(self, form):
        form.instance.creator = self.request.user
        form.save()
        return super().form_valid(form)
    
class QuizDeleteView(LoginRequiredMixin,DeleteView):
    model = models.Quiz
    template_name = 'quiz/quiz_confirm_delete.html'
    success_url = reverse_lazy('quiz:quiz-list')

    
    
    
class QuestionCreateUpdateView(TemplateResponseMixin,View):
    template_name = 'quiz/question_form.html'
    obj = None
    model = None
    
    def get_model(self, model_name):
        if model_name in ['textquestion', 'optionquestion','booleanquestion']:
            return apps.get_model(
                app_label='quiz', model_name=model_name
            )
        raise Http404
    
    def dispatch(self,request,quiz_pk,model_name,pk=None):
        self.quiz = get_object_or_404(
            models.Quiz, pk=quiz_pk
            )
        self.model = self.get_model(model_name)
        if pk :
            self.obj = get_object_or_404(
                self.model, pk=pk
                )
        
        return super().dispatch(request,quiz_pk,model_name,pk)
    
    def get_form(self, model, *args, **kwargs):
        
        Form = modelform_factory(
            model, fields=['title','time_limit','image'])
        return Form(*args, **kwargs)

    def get(self,request,quiz_pk,model_name,pk=None):

        formset = None
        if self.model == models.OptionQuestion :
            formset = OptionFormSet(instance=self.obj)
        form = self.get_form(self.model, instance=self.obj)
        return self.render_to_response(
            {'form': form, 'object': self.obj,'formset':formset}
        )
    
    def post(self,request,quiz_pk,model_name,pk=None):
        form = self.get_form(
            self.model,
            instance=self.obj,
            data=request.POST,
            files=request.FILES,
        )

        if form.is_valid() :
            obj = form.save(commit=False)
            obj.creator = request.user
            obj.save()
            if not pk:
                models.Question.objects.create(quiz=self.quiz, item=obj)
            if self.model == models.OptionQuestion:
                formset = OptionFormSet(request.POST,instance=obj)
                if not formset.is_valid() :
                    return self.render_to_response(
                {'form': form, 'object': self.obj}
                )
                formset.save()
            return redirect('quiz:quiz-detail', self.quiz.pk)
        return self.render_to_response(
                    {'form': form, 'object': self.obj}
                )

class QuestionDeleteView(View):
    
    def post(self,request,pk):
        question = get_object_or_404(models.Question,id=pk)
        question.item.delete()
        question.delete()
        return redirect('quiz:quiz-detail',question.quiz.pk)
    
class AnswerCreateView(View):
    def post(self,request,question_id):
        question = get_object_or_404(models.Question,id=question_id)
        answer = request.POST.get('answer')
        if answer:
            try:
                models.Answer.objects.create(question=question,title=answer)
            except IntegrityError:
                messages.error(request, "This answer already exist")
        return redirect('quiz:quiz-detail',question.quiz.pk)
        


            
        

templates/quiz/question_form.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}
  <h1>
    {% if object %}
      {% translate "Edit question" %} "{{ object.title }}"
    {% else %}
      {% translate "Add new question" %}
    {% endif %}
  </h1>

    <form action="" method="post" enctype="multipart/form-data">
      {{ form.as_p }}

      {% if formset %}
      <h3>{% translate "Options" %}:</h3>
        {{ formset.management_form }}
          {% for form in formset %}
              {{ form.as_p }}
          {% endfor %}
      {% endif %}
      {% csrf_token %}
      <button type="submit" class="small-gray-btn">{% translate "Save question" %} </button>
    </form>

{% endblock %}

templates/quiz/quiz_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}

<div class='container'>

    <h2>{% translate "Delete quiz" %}</h2>
    <p>{% translate "Are you sure you want to delete quiz" %}  {{object.title}} </p>

    <form method='post'>
        {% csrf_token %}
        <button type='submit' class='btn btn-danger'>{% translate "Yes, delete" %} </button>
        <a href='{% url "quiz:quiz-list"   %}' > {% translate "No" %} </a >
    </form>

</div>

{% endblock content %}

templates/quiz/quiz_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load custom_tags %}


{% block content %}
<h1>{{quiz}}</h1>

{% for question in quiz.questions.all %}
    {% with item=question.item %}

    <div class="survey-card">
    <div class="card-body">
        <h5 class="survey-card-title">{{ item.title }}</h5>
        {% for answer in question.answers.all %}
            {{answer}}
        {% endfor %}
        <p class="survey-card-text">
        {% if item|model_name == 'optionquestion' %}
            <ul>
            {% for option in item.options.all %}
                <li>{{ option }}</li>
            {% endfor %}
            </ul>
        {% endif %}
        </p>

        <form method='post' action='{% url "quiz:answer-create" question.pk %}'> 
            {% csrf_token %}
            <input type="text" id="answer" name="answer" value=""><br>
            <button type="submit">{% translate "Add answer" %}</button>
        </form>

        <a href="{% url 'quiz:question-update' quiz.id item|model_name item.id %}">
        {% translate "Edit" %}
        </a>
        
        <form method='post' action='{% url "quiz:question-delete" question.pk %}'>
        {% csrf_token %}
        <button type="submit">{% translate "Delete question" %}</button>
        </form> 

    </div>
    </div>

    <br>
    {% endwith %}
{% endfor %}

<ul>
    <li><a href='{% url "quiz:question-create" quiz.pk "textquestion"  %}' >{% translate "Create text question" %}</a></li>
    <li><a href='{% url "quiz:question-create" quiz.pk "optionquestion"  %}' >{% translate "Create option question" %}</a></li>
    <li><a href='{% url "quiz:question-create" quiz.pk "booleanquestion"  %}' >{% translate "Create true or false question" %}</a></li>
</ul>

 <form action="{% url 'quiz_session:create-session' quiz.pk %}" method="post"  >
    {% csrf_token %}
    <button type="submit" class="small-gray-btn">{% translate "Host live" %} </button>
</form> 


{% endblock content %}

templates/quiz/quiz_form.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}
{{request.kwargs.pk}}
  {% comment %} <h1>
    {% if object %}
      {% translate "Edit content" %} "{{ object.title }}"
    {% else %}
      {% translate "Add new question" %}
    {% endif %} {% endcomment %}
  </h1>

    <form action="" method="post" enctype="multipart/form-data">
      {{ form.as_p }}
      {% csrf_token %}
      <button type="submit" class="small-gray-btn">{% translate "Save quiz" %} </button>
    </form>

{% endblock %}

templates/quiz/quiz_list.html
{% extends "base.html" %}
{% load i18n %}



{% block content %}

{% for quiz in quizzes %}
        <a href ='{% url "quiz:quiz-detail" quiz.pk %}' >{{quiz}}</a>
        <div class="project-item-set">
            <a href='{% url "quiz:quiz-delete" quiz.pk %}' class="custom-small-gray-btn">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"></path>
                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"></path>
                </svg>
            </a>
            <a href='{% url "quiz:quiz-update" quiz.pk %}' class="custom-small-gray-btn">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325"></path>
                </svg>
            </a>
        </div>
        <br>

    {% empty %}

        <h3>{% translate "No quizzes yet" %} </h3>

{% endfor %}


    <a href='{% url "quiz:quiz-create" %}' class="btn btn-primary btn-lg">
        {% translate "Create new quiz" %}
    </a>


{% endblock content %}